Refactor Project
addisalemseifu/bookstore3 pull request #2
Opened 2023-03-22 18:02 UTC by addisalemseifu

-make the book list background alternating background color.
-put all the functionalities in a function.
-edit the styling so that it will look like the example.
-did the project solo because I was instructed to do so.
![Untitled](https://user-images.githubusercontent.com/65928536/227099531-ee6e5e18-fc47-41b4-9721-073b34b23df8.png)

2023-03-22 18:12 UTC, huseyinbiyik commented
Hi @addisalemseifu 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

You have submitted a project, that has no visible contribution from your pair programming partner. Kindly check the Work and Submission mode on the project requirements.
<img width="936" alt="Screenshot 2023-03-22 at 9 11 21 PM" src="https://user-images.githubusercontent.com/25887253/226998901-436d37ce-19ca-457c-9880-9805e800d464.png">




Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-22 19:19 UTC, rloterh reviewed
Hi Addisalem, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is not contributed by all assigned pair group members. Kindly ensure that all assigned members to this project contribute evenly to this task, and then request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-23 04:28 UTC, jasonfelice requested changes
Hi @addisalemseifu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
No Linter errors✔️
Good Job with the design✔️
Descriptive PR✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 04:28 UTC, jasonfelice commented on script.js
> +}
- [ ] It seems like you are not using JavaScript classes. Kindly, refactor your code to make sure you are using `class`.
_Consider the following example:_
```
class Books {
  constructor() {
    this.books = [];
  }
    //  Here you will define all the methods. Here's an example.
    
    addbook(title, author) {
      // Code to add the book to `this.books`
    }
 }
```
_Remember, this is just an example_

2023-03-23 08:52 UTC, Abenezer-Tilahun commented on script.js
> +}
Fixed.

2023-03-23 08:59 UTC, Abenezer-Tilahun approved these changes
Hi @addisalemseifu 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git Hub-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.

## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 10:06 UTC, merged